import {
  Property,
  MockUser,
  WhatsAppResponseRecord,
  PublishQueueItem,
  PublishHistoryItem,
} from './types'

export const MOCK_USER: MockUser = {
  id: 'user-1',
  nombre: 'Carlos Mendoza',
  email: 'carlos@inmobiliariapanama.com',
  planId: 'pro',
  agencia: 'Inmobiliaria Panamá',
}

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    wasi_id: '10001',
    titulo: 'Penthouse con vista al mar en Punta Pacífica',
    precio: 850000,
    tipo: 'venta',
    for_sale: true,
    for_rent: false,
    estado_publicacion: 'destacado',
    disponibilidad: 'disponible',
    id_status_on_page: '3',
    status_on_page_label: 'Outstanding',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'wasi',
    property_type_label: 'Penthouse',
    id_property_condition: '1',
    property_condition_label: 'New',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Punta Pacífica',
    address: 'Av. Balboa, Torre Oceánica, PH-2801',
    latitude: '8.9786',
    longitude: '-79.5187',
    iso_currency: 'USD',
    name_currency: 'Dólares Americanos',
    sale_price: 850000,
    sale_price_label: '$850,000',
    area: '280',
    unit_area_label: 'M2',
    built_area: '280',
    bedrooms: 3,
    bathrooms: 3,
    half_bathrooms: 1,
    garages: 2,
    floor: '28',
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80'],
    main_image: {
      url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      url_big: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=90',
    },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80', position: '1' },
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', position: '2' },
      { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80', position: '3' },
    ],
    features: {
      internal: [
        { id: '5', nombre: 'Balcón' },
        { id: '10', nombre: 'Jacuzzi' },
        { id: '22', nombre: 'Vista al mar' },
      ],
      external: [
        { id: '78', nombre: 'Área social' },
        { id: '80', nombre: 'Piscina' },
      ],
    },
    visits: 342,
    network_share: true,
    descripcion: 'Impresionante penthouse de 280m² con vista panorámica al océano Pacífico. 3 habitaciones, 3.5 baños, terraza privada.',
    telefono_propietario: '+507 6123-4567',
    canalesPublicados: ['facebook'],
    fechaCreacion: '2026-04-01T10:00:00Z',
    whatsappEstado: 'disponible',
    etapa_crm: 'negociando',
    cliente_nombre: 'Roberto Sánchez',
    cliente_email: 'roberto.sanchez@email.com',
    agente_asignado: 'Carlos Mendoza',
    fecha_seguimiento: '2026-05-20',
    notas: 'Cliente muy interesado. Ofreció $820k. Propietario evalúa.',
    brevo_deal_id: null,
  },
  {
    id: 'prop-2',
    wasi_id: '10002',
    titulo: 'Apartamento moderno en Costa del Este',
    precio: 620000,
    tipo: 'venta',
    for_sale: true,
    for_rent: false,
    estado_publicacion: 'activo',
    disponibilidad: 'disponible',
    id_status_on_page: '1',
    status_on_page_label: 'Active',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'wasi',
    property_type_label: 'Apartamento',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Costa del Este',
    address: 'Blvd. Costa del Este, Torre Vitri, Apto 1502',
    iso_currency: 'USD',
    sale_price: 620000,
    sale_price_label: '$620,000',
    area: '180',
    unit_area_label: 'M2',
    bedrooms: 2,
    bathrooms: 2,
    garages: 2,
    floor: '15',
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', position: '1' },
      { url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80', position: '2' },
    ],
    features: {
      internal: [
        { id: '4', nombre: 'Amoblado' },
        { id: '84', nombre: 'Armarios empotrados' },
      ],
      external: [
        { id: '80', nombre: 'Piscina' },
        { id: '81', nombre: 'Gimnasio' },
      ],
    },
    visits: 187,
    descripcion: 'Apartamento de lujo 180m², 2 habitaciones master, acabados de primera, piscina y gimnasio en el edificio.',
    telefono_propietario: '+507 6234-5678',
    canalesPublicados: ['facebook'],
    fechaCreacion: '2026-04-05T14:30:00Z',
    whatsappEstado: 'contactado',
    etapa_crm: 'visita',
    cliente_nombre: 'María González',
    cliente_email: 'maria.gonzalez@corp.com',
    agente_asignado: 'Ana Rodríguez',
    fecha_seguimiento: '2026-05-18',
    notas: 'Visita programada para el sábado 18 de mayo a las 10am.',
    brevo_deal_id: null,
  },
  {
    id: 'prop-3',
    wasi_id: '10003',
    titulo: 'Loft histórico en Casco Viejo',
    precio: 2800,
    tipo: 'arriendo',
    for_sale: false,
    for_rent: true,
    estado_publicacion: 'destacado',
    disponibilidad: 'disponible',
    id_status_on_page: '3',
    status_on_page_label: 'Outstanding',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'manual',
    property_type_label: 'Loft',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Casco Viejo',
    address: 'Calle 4a, Edificio Patrimonial, Loft 301',
    iso_currency: 'USD',
    rent_price: 2800,
    rent_price_label: '$2,800/mes',
    id_rents_type: '4',
    rents_type_label: 'Monthly',
    area: '90',
    unit_area_label: 'M2',
    bedrooms: 1,
    bathrooms: 1,
    garages: 1,
    floor: '3',
    furnished: true,
    video: 'https://vimeo.com/example123',
    imagenes: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', position: '1' },
      { url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80', position: '2' },
    ],
    features: {
      internal: [
        { id: '4', nombre: 'Amoblado' },
        { id: '5', nombre: 'Balcón' },
      ],
      external: [
        { id: '78', nombre: 'Área social' },
      ],
    },
    visits: 94,
    descripcion: 'Loft de diseño en edificio patrimonial restaurado. 90m², 1 habitación, techos altos, vistas a la bahía.',
    telefono_propietario: '+507 6345-6789',
    canalesPublicados: ['facebook'],
    fechaCreacion: '2026-04-10T09:15:00Z',
    whatsappEstado: 'disponible',
    etapa_crm: 'oferta',
    cliente_nombre: 'Pedro Herrera',
    cliente_email: 'pedro.herrera@gmail.com',
    agente_asignado: 'Carlos Mendoza',
    fecha_seguimiento: '2026-05-19',
    notas: 'Oferta enviada $2,600/mes. Esperando respuesta del propietario.',
    brevo_deal_id: null,
  },
  {
    id: 'prop-4',
    wasi_id: '10004',
    titulo: 'Casa familiar en Miraflores',
    precio: 390000,
    tipo: 'venta',
    for_sale: true,
    for_rent: false,
    estado_publicacion: 'activo',
    disponibilidad: 'disponible',
    id_status_on_page: '1',
    status_on_page_label: 'Active',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'wasi',
    property_type_label: 'Casa',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Miraflores',
    address: 'Calle Miraflores, Casa #47',
    iso_currency: 'USD',
    sale_price: 390000,
    sale_price_label: '$390,000',
    area: '250',
    unit_area_label: 'M2',
    built_area: '200',
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80', position: '1' },
    ],
    features: {
      internal: [
        { id: '2', nombre: 'Alarma' },
        { id: '84', nombre: 'Armarios empotrados' },
      ],
      external: [
        { id: '70', nombre: 'Jardín' },
        { id: '85', nombre: 'Cuarto de empleada' },
      ],
    },
    visits: 56,
    descripcion: 'Casa de 250m², 4 habitaciones, 3 baños, jardín privado, cuarto de empleada, 2 estacionamientos.',
    telefono_propietario: '+507 6456-7890',
    canalesPublicados: [],
    fechaCreacion: '2026-04-15T11:00:00Z',
    whatsappEstado: 'no_contactado',
    etapa_crm: 'contactado',
    cliente_nombre: 'Laura Méndez',
    cliente_email: 'laura.mendez@hotmail.com',
    agente_asignado: 'Ana Rodríguez',
    fecha_seguimiento: '2026-05-22',
    notas: 'Primer contacto hecho. Le enviamos brochure digital.',
    brevo_deal_id: null,
  },
  {
    id: 'prop-5',
    wasi_id: '10005',
    titulo: 'Estudio en San Francisco',
    precio: 1500,
    tipo: 'arriendo',
    for_sale: false,
    for_rent: true,
    estado_publicacion: 'activo',
    disponibilidad: 'disponible',
    id_status_on_page: '1',
    status_on_page_label: 'Active',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'manual',
    property_type_label: 'Estudio',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'San Francisco',
    address: 'Vía Brasil, Edificio San Marino, Apto 504',
    iso_currency: 'USD',
    rent_price: 1500,
    rent_price_label: '$1,500/mes',
    id_rents_type: '4',
    rents_type_label: 'Monthly',
    area: '55',
    unit_area_label: 'M2',
    bedrooms: 1,
    bathrooms: 1,
    garages: 1,
    furnished: true,
    imagenes: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80', position: '1' },
    ],
    features: {
      internal: [{ id: '4', nombre: 'Amoblado' }],
      external: [{ id: '81', nombre: 'Gimnasio' }],
    },
    visits: 23,
    descripcion: 'Estudio completamente amoblado de 55m², a pasos del metro San Francisco. Ideal para profesionales.',
    telefono_propietario: '+507 6567-8901',
    canalesPublicados: [],
    fechaCreacion: '2026-04-20T16:45:00Z',
    whatsappEstado: 'no_contactado',
    etapa_crm: 'prospecto',
    cliente_nombre: null,
    cliente_email: null,
    agente_asignado: null,
    fecha_seguimiento: null,
    notas: null,
    brevo_deal_id: null,
  },
  {
    id: 'prop-6',
    wasi_id: '10006',
    titulo: 'Apartamento en Bella Vista',
    precio: 275000,
    tipo: 'venta',
    for_sale: true,
    for_rent: false,
    estado_publicacion: 'activo',
    disponibilidad: 'disponible',
    id_status_on_page: '1',
    status_on_page_label: 'Active',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'wasi',
    property_type_label: 'Apartamento',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Bella Vista',
    address: 'Av. Federico Boyd, Torre Bella, Apto 802',
    iso_currency: 'USD',
    sale_price: 275000,
    sale_price_label: '$275,000',
    area: '110',
    unit_area_label: 'M2',
    bedrooms: 2,
    bathrooms: 2,
    garages: 1,
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80', position: '1' },
    ],
    features: {
      internal: [{ id: '2', nombre: 'Alarma' }],
      external: [{ id: '86', nombre: 'BBQ' }],
    },
    visits: 41,
    descripcion: 'Apartamento de 110m², 2 habitaciones, 2 baños. Edificio con seguridad 24h, área de bbq.',
    telefono_propietario: '+507 6678-9012',
    canalesPublicados: [],
    fechaCreacion: '2026-04-22T08:30:00Z',
    whatsappEstado: 'no_contactado',
    etapa_crm: 'prospecto',
    cliente_nombre: null,
    cliente_email: null,
    agente_asignado: 'Carlos Mendoza',
    fecha_seguimiento: '2026-05-25',
    notas: 'Error de publicación por token expirado. Re-intentar.',
    brevo_deal_id: null,
  },
  {
    id: 'prop-7',
    wasi_id: '10007',
    titulo: 'Villa en Santa María Golf & Country Club',
    precio: 745000,
    tipo: 'venta',
    for_sale: true,
    for_rent: false,
    estado_publicacion: 'destacado',
    disponibilidad: 'vendido',
    id_status_on_page: '3',
    status_on_page_label: 'Outstanding',
    id_availability: '2',
    availability_label: 'Sold',
    fuente: 'wasi',
    property_type_label: 'Villa',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Santa María',
    address: 'Santa María Golf & Country Club, Lote 42',
    iso_currency: 'USD',
    sale_price: 745000,
    sale_price_label: '$745,000',
    area: '400',
    unit_area_label: 'M2',
    built_area: '350',
    bedrooms: 5,
    bathrooms: 4,
    half_bathrooms: 1,
    garages: 3,
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', position: '1' },
      { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80', position: '2' },
    ],
    features: {
      internal: [
        { id: '10', nombre: 'Jacuzzi' },
        { id: '11', nombre: 'Chimenea' },
      ],
      external: [
        { id: '80', nombre: 'Piscina' },
        { id: '70', nombre: 'Jardín' },
        { id: '87', nombre: 'Campo de golf' },
      ],
    },
    visits: 521,
    network_share: true,
    descripcion: 'Villa de lujo 400m² en el exclusivo club de golf. 5 habitaciones, piscina privada, jardín tropical.',
    telefono_propietario: '+507 6789-0123',
    canalesPublicados: ['facebook'],
    fechaCreacion: '2026-03-15T10:00:00Z',
    whatsappEstado: 'vendida',
    etapa_crm: 'cerrado',
    cliente_nombre: 'Ana Martínez',
    cliente_email: 'ana.martinez@empresa.com',
    agente_asignado: 'Carlos Mendoza',
    fecha_seguimiento: null,
    notas: 'CERRADO — Venta completada el 8 de mayo 2026. Comisión 3%.',
    brevo_deal_id: 'brv-deal-7890',
  },
  {
    id: 'prop-8',
    wasi_id: '10008',
    titulo: 'Apartamento en Clayton',
    precio: 900,
    tipo: 'arriendo',
    for_sale: false,
    for_rent: true,
    estado_publicacion: 'inactivo',
    disponibilidad: 'alquilado',
    id_status_on_page: '2',
    status_on_page_label: 'Inactive',
    id_availability: '3',
    availability_label: 'Rented',
    fuente: 'manual',
    property_type_label: 'Apartamento',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Clayton',
    address: 'Ciudad del Saber, Clayton, Edif. B, Apto 12',
    iso_currency: 'USD',
    rent_price: 900,
    rent_price_label: '$900/mes',
    id_rents_type: '4',
    rents_type_label: 'Monthly',
    area: '70',
    unit_area_label: 'M2',
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80', position: '1' },
    ],
    features: {
      internal: [{ id: '3', nombre: 'Aire acondicionado' }],
      external: [{ id: '88', nombre: 'Zona verde' }],
    },
    visits: 68,
    descripcion: 'Apartamento 70m², 2 habitaciones, 1 baño. Zona verde, tranquila, cerca de universidades.',
    telefono_propietario: '+507 6890-1234',
    canalesPublicados: [],
    fechaCreacion: '2026-03-01T12:00:00Z',
    whatsappEstado: 'no_disponible',
    etapa_crm: 'cerrado',
    cliente_nombre: 'Luis Rodríguez',
    cliente_email: null,
    agente_asignado: 'Ana Rodríguez',
    fecha_seguimiento: null,
    notas: 'Arrendado. Inquilino: Luis Rodríguez. Contrato 1 año.',
    brevo_deal_id: null,
  },
  {
    id: 'prop-9',
    wasi_id: '10009',
    titulo: 'Apartamento económico en Miraflores',
    precio: 150000,
    tipo: 'venta',
    for_sale: true,
    for_rent: false,
    estado_publicacion: 'activo',
    disponibilidad: 'disponible',
    id_status_on_page: '1',
    status_on_page_label: 'Active',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'manual',
    property_type_label: 'Apartamento',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Miraflores',
    address: 'Calle 50, Residencial Miraflores, Apto 301',
    iso_currency: 'USD',
    sale_price: 150000,
    sale_price_label: '$150,000',
    area: '65',
    unit_area_label: 'M2',
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    furnished: false,
    imagenes: ['https://images.unsplash.com/photo-1551361415-69c87624334f?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1551361415-69c87624334f?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1551361415-69c87624334f?w=800&q=80', position: '1' },
    ],
    features: {
      internal: [{ id: '3', nombre: 'Aire acondicionado' }],
      external: [],
    },
    visits: 12,
    descripcion: 'Apartamento de 65m², 2 habitaciones, 1 baño. Primera compra ideal, financiamiento disponible.',
    telefono_propietario: '+507 6901-2345',
    canalesPublicados: [],
    fechaCreacion: '2026-05-01T09:00:00Z',
    whatsappEstado: 'no_contactado',
    etapa_crm: 'prospecto',
    cliente_nombre: null,
    cliente_email: null,
    agente_asignado: null,
    fecha_seguimiento: null,
    notas: null,
    brevo_deal_id: null,
  },
  {
    id: 'prop-10',
    wasi_id: '10010',
    titulo: 'Ático premium en Punta Pacífica',
    precio: 3500,
    tipo: 'arriendo',
    for_sale: false,
    for_rent: true,
    estado_publicacion: 'destacado',
    disponibilidad: 'disponible',
    id_status_on_page: '3',
    status_on_page_label: 'Outstanding',
    id_availability: '1',
    availability_label: 'Available',
    fuente: 'wasi',
    property_type_label: 'Ático',
    country_label: 'Panamá',
    ciudad: 'Ciudad de Panamá',
    zona: 'Punta Pacífica',
    address: 'Av. Balboa, Torre Aqua, PH-3200',
    iso_currency: 'USD',
    rent_price: 3500,
    rent_price_label: '$3,500/mes',
    id_rents_type: '4',
    rents_type_label: 'Monthly',
    area: '200',
    unit_area_label: 'M2',
    bedrooms: 3,
    bathrooms: 2,
    half_bathrooms: 1,
    garages: 2,
    floor: '32',
    furnished: true,
    imagenes: ['https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80'],
    main_image: { url: 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80' },
    galleries: [
      { url: 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80', position: '1' },
      { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80', position: '2' },
    ],
    features: {
      internal: [
        { id: '4', nombre: 'Amoblado' },
        { id: '22', nombre: 'Vista al mar' },
        { id: '5', nombre: 'Balcón' },
      ],
      external: [
        { id: '80', nombre: 'Piscina' },
        { id: '89', nombre: 'Concierge' },
      ],
    },
    visits: 203,
    network_share: true,
    descripcion: 'Ático amoblado de 200m², 3 habitaciones, vistas al mar y ciudad. Edificio de lujo con concierge.',
    telefono_propietario: '+507 6012-3456',
    canalesPublicados: ['facebook'],
    fechaCreacion: '2026-04-28T14:00:00Z',
    whatsappEstado: 'contactado',
    etapa_crm: 'contactado',
    cliente_nombre: 'Sofía Vargas',
    cliente_email: 'sofia.vargas@outlook.com',
    agente_asignado: 'Carlos Mendoza',
    fecha_seguimiento: '2026-05-21',
    notas: 'Interesada para 6 meses. Trabaja en embajada.',
    brevo_deal_id: null,
  },
]

export const MOCK_WHATSAPP_RESPONSES: WhatsAppResponseRecord[] = [
  {
    id: 'wa-1',
    propertyId: 'prop-1',
    propietario: 'Roberto Sánchez',
    telefono: '+507 6123-4567',
    respuesta: 'disponible',
    fecha: '2026-05-10T10:30:00Z',
    accionTomada: 'Duplicada y publicada en portales',
  },
  {
    id: 'wa-2',
    propertyId: 'prop-2',
    propietario: 'María González',
    telefono: '+507 6234-5678',
    respuesta: 'sin_respuesta',
    fecha: '2026-05-09T15:00:00Z',
    accionTomada: null,
  },
  {
    id: 'wa-3',
    propertyId: 'prop-3',
    propietario: 'Pedro Herrera',
    telefono: '+507 6345-6789',
    respuesta: 'disponible',
    fecha: '2026-05-11T09:00:00Z',
    accionTomada: 'Duplicada y publicada en portales',
  },
  {
    id: 'wa-4',
    propertyId: 'prop-7',
    propietario: 'Ana Martínez',
    telefono: '+507 6789-0123',
    respuesta: 'vendida',
    fecha: '2026-05-08T11:00:00Z',
    accionTomada: 'Movida a papelera',
  },
  {
    id: 'wa-5',
    propertyId: 'prop-8',
    propietario: 'Luis Rodríguez',
    telefono: '+507 6890-1234',
    respuesta: 'no_disponible',
    fecha: '2026-05-07T16:30:00Z',
    accionTomada: 'Inactivada',
  },
]

export const MOCK_QUEUE: PublishQueueItem[] = [
  {
    id: 'q-1',
    propertyId: 'prop-4',
    propertyTitulo: 'Casa familiar en Miraflores',
    canal: 'Facebook Marketplace',
    programadoPara: '2026-05-12T18:00:00Z',
    estado: 'pendiente',
  },
  {
    id: 'q-2',
    propertyId: 'prop-5',
    propertyTitulo: 'Estudio en San Francisco',
    canal: 'Facebook Marketplace',
    programadoPara: '2026-05-12T18:05:00Z',
    estado: 'pendiente',
  },
  {
    id: 'q-3',
    propertyId: 'prop-9',
    propertyTitulo: 'Apartamento económico en Miraflores',
    canal: 'Facebook Marketplace',
    programadoPara: '2026-05-12T18:10:00Z',
    estado: 'en_proceso',
  },
]

export const MOCK_HISTORY: PublishHistoryItem[] = [
  {
    id: 'h-1',
    propertyId: 'prop-1',
    propertyTitulo: 'Penthouse con vista al mar en Punta Pacífica',
    canal: 'Facebook Marketplace',
    fecha: '2026-05-11T10:00:00Z',
    estado: 'exitoso',
  },
  {
    id: 'h-2',
    propertyId: 'prop-2',
    propertyTitulo: 'Apartamento moderno en Costa del Este',
    canal: 'Facebook Marketplace',
    fecha: '2026-05-11T10:05:00Z',
    estado: 'exitoso',
  },
  {
    id: 'h-3',
    propertyId: 'prop-6',
    propertyTitulo: 'Apartamento en Bella Vista',
    canal: 'Facebook Marketplace',
    fecha: '2026-05-10T14:00:00Z',
    estado: 'fallido',
    error: 'Token de acceso expirado',
  },
  {
    id: 'h-4',
    propertyId: 'prop-3',
    propertyTitulo: 'Loft histórico en Casco Viejo',
    canal: 'Facebook Marketplace',
    fecha: '2026-05-10T09:00:00Z',
    estado: 'exitoso',
  },
  {
    id: 'h-5',
    propertyId: 'prop-7',
    propertyTitulo: 'Villa en Santa María Golf & Country Club',
    canal: 'Facebook Marketplace',
    fecha: '2026-05-09T11:00:00Z',
    estado: 'exitoso',
  },
]
